defaults:
  - override hydra/hydra_logging: disabled

# Model configuration
model:
  name: CustomCNN

# WandB configuration
wandb:
  project: "pytorch_tutorial"  # Replace with your actual project name
  entity: "cbrain"      # Replace with your actual entity name
  run_name: "command_line_test"  # Define a run name or leave it dynamic

# Training configuration
training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 3
  optimizer: "Adam"
