_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 50
                - 55
            "2":
                - 1
                - 41
                - 50
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": darwin-arm64
batch_size:
    value: 64
learning_rate:
    value: 0.001
model_name:
    value: CustomCNN
num_epochs:
    value: 3
optimizer:
    value: Adam
